services:
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  db:
    build: ./db
    container_name: postgres-db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=greetings_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
